<?php

/**
 * NanoAgent Basic Usage Example
 * 
 * Demonstrates the fundamental steps to initialize an agent, define a custom tool,
 * and execute a high-level task with contextual data.
 */

declare(strict_types=1);

require_once __DIR__ . '/../NanoAgent/autoloader.php';

use NanoAgent\Agent;
use NanoAgent\Task;
use NanoAgent\Tools\FunctionTool;

// Start output buffering to capture log messages for the web display.
ob_start();

try {
    // 1. Configuration Handling
    // Loads the default configuration (API key, provider, model) from the library.
    $configFile = __DIR__ . '/../NanoAgent/config.php';
    $config = file_exists($configFile) ? require $configFile : [];

    // 2. Define a Custom Tool
    // Tools are PHP callables that the AI can choose to invoke based on its instructions.
    // We use JSON Schema to describe the expected parameters to the LLM.
    $secretTool = new FunctionTool(
        name: 'generate_secret_token',
        description: 'Generates a secure token based on input string. Useful for simulation.',
        parameters: [
            'type' => 'object',
            'properties' => [
                'input' => ['type' => 'string', 'description' => 'The string to be obfuscated into a token']
            ],
            'required' => ['input']
        ],
        callable: fn(array $args) => "TOKEN_" . strtoupper(strrev($args['input'])) . "_SECURE"
    );

    // 3. Initialize the Agent
    // The Agent is the core component that manages the conversation with the AI provider.
    $llmConfig = [
        'provider' => $config['provider'] ?? 'groq',
        'model'    => $config['model']    ?? 'llama-3.3-70b-versatile',
        'api_key'  => $config['api_key']  ?? ''
    ];

    $agent = new Agent(
        llm: $llmConfig,
        systemPrompt: "You are a helpful PHP technical assistant.",
        tools: [$secretTool] // Register our custom tool.
    );

    // 4. Create and Execute a Task
    // The Task class provides a convenient wrapper to bundle a goal with background context.
    $task = new Task($agent);
    
    // Inject background context that the agent will refer to during execution.
    $task->addContext("Project", "NanoAgent Library");
    
    echo "Starting task execution...\n";
    
    // Execute the task. Under the hood, this formats the goal and context 
    // into a single prompt and handles any tool calls generated by the AI.
    $response = $task->execute("Generate a secret token for 'NanoAgent' and explain how it was created.");
    
    // Retrieve the captured log output.
    $output = ob_get_clean();

} catch (\Throwable $e) {
    // Ensure the buffer is cleared and error is captured.
    $output = ob_get_clean();
    $error = $e->getMessage();
}

// Display Web UI
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Basic Example - NanoAgent</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="container">
        <div class="header">
            <a href="index.php" class="nav-back">Back to Examples</a>
            <h1>Basic Example</h1>
            <p>A simple demonstration of Agent task processing.</p>
        </div>

        <?php include __DIR__ . '/components/agent_config.php'; ?>

        <?php if (isset($error)): ?>
            <div class="error-box">
                <strong>Error:</strong> <?php echo htmlspecialchars($error); ?>
            </div>
        <?php endif; ?>

        <?php if (isset($response)): ?>
            <div class="card">
                <h2>🤖 AI Response</h2>
                <div class="response-box"><?php echo nl2br(htmlspecialchars($response)); ?></div>
            </div>
        <?php endif; ?>

        <div class="card">
            <h2>📜 Execution Log</h2>
            <div class="log-box"><?php echo htmlspecialchars($output); ?></div>
        </div>

    </div>
</body>
</html>

